// programs/tessera/build-verifier-constants.ts
// Generate src/verifier_constants.rs from circuits/verification_key.json,
// in the byte layout groth16-solana 0.2.0 expects.
//
// Convention (per Lightprotocol/groth16-solana parser):
//   - vk fields are decimal strings of BN254 field elements
//   - we emit each component as an array of u8 in big-endian order
//   - G1 points: [x, y] each 32 bytes BE => 64 bytes total
//   - G2 points: [x.c1, x.c0, y.c1, y.c0] each 32 bytes BE => 128 bytes total
//     (note the c1-before-c0 ordering matches the Solana alt_bn128 syscall ABI)

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const HERE = join(__filename, "..");
const ROOT = join(HERE, "..", "..");
const VK_PATH = join(ROOT, "circuits", "verification_key.json");
const OUT_PATH = join(HERE, "src", "verifier_constants.rs");

interface Vk {
  protocol: string;
  curve: string;
  nPublic: number;
  vk_alpha_1: string[];        // G1 affine: [x, y, 1]
  vk_beta_2: string[][];       // G2 affine: [[x.c0, x.c1], [y.c0, y.c1], [1,0]]
  vk_gamma_2: string[][];
  vk_delta_2: string[][];
  IC: string[][];              // each is G1 affine [x, y, 1]
}

function decToBytesBe32(decimal: string): Uint8Array {
  const v = BigInt(decimal);
  if (v < 0n) throw new Error("negative field element");
  const out = new Uint8Array(32);
  let x = v;
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(x & 0xFFn);
    x >>= 8n;
  }
  if (x !== 0n) throw new Error(`field element overflows 32 bytes: ${decimal}`);
  return out;
}

function g1ToBytes(p: string[]): Uint8Array {
  if (p.length < 2) throw new Error("G1 point: expected [x, y]");
  const x = decToBytesBe32(p[0]);
  const y = decToBytesBe32(p[1]);
  const out = new Uint8Array(64);
  out.set(x, 0);
  out.set(y, 32);
  return out;
}

function g2ToBytes(p: string[][]): Uint8Array {
  if (p.length < 2 || p[0].length < 2 || p[1].length < 2) {
    throw new Error("G2 point: expected [[x.c0, x.c1], [y.c0, y.c1]]");
  }
  // groth16-solana / Solana alt_bn128 order: [x.c1, x.c0, y.c1, y.c0]
  const x_c1 = decToBytesBe32(p[0][1]);
  const x_c0 = decToBytesBe32(p[0][0]);
  const y_c1 = decToBytesBe32(p[1][1]);
  const y_c0 = decToBytesBe32(p[1][0]);
  const out = new Uint8Array(128);
  out.set(x_c1, 0);
  out.set(x_c0, 32);
  out.set(y_c1, 64);
  out.set(y_c0, 96);
  return out;
}

function bytesToRustArray(bytes: Uint8Array, perLine = 16): string {
  const lines: string[] = [];
  for (let i = 0; i < bytes.length; i += perLine) {
    const slice = bytes.slice(i, i + perLine);
    lines.push("    " + Array.from(slice).map(b => b.toString().padStart(3, " ")).join(", ") + ",");
  }
  return lines.join("\n");
}

function emitG1(name: string, bytes: Uint8Array): string {
  return `pub const ${name}: [u8; 64] = [\n${bytesToRustArray(bytes)}\n];`;
}

function emitG2(name: string, bytes: Uint8Array): string {
  return `pub const ${name}: [u8; 128] = [\n${bytesToRustArray(bytes)}\n];`;
}

function emitIC(points: string[][]): string {
  const blocks: string[] = [];
  for (let i = 0; i < points.length; i++) {
    const bytes = g1ToBytes(points[i]);
    blocks.push(`    [\n${bytesToRustArray(bytes, 16).split("\n").map(l => "    " + l).join("\n")}\n    ],`);
  }
  return `pub const VK_IC: [[u8; 64]; ${points.length}] = [\n${blocks.join("\n")}\n];`;
}

function main() {
  const vk: Vk = JSON.parse(readFileSync(VK_PATH, "utf8"));
  if (vk.protocol !== "groth16") throw new Error(`unexpected protocol: ${vk.protocol}`);
  if (vk.curve !== "bn128") throw new Error(`unexpected curve: ${vk.curve}`);

  const expectedNPublic = 39;
  if (vk.nPublic !== expectedNPublic) {
    console.error(`BLOCKER: vk.nPublic=${vk.nPublic} but circuit expects ${expectedNPublic}`);
    process.exit(2);
  }
  if (vk.IC.length !== vk.nPublic + 1) {
    console.error(`BLOCKER: IC.length=${vk.IC.length} but expected nPublic+1=${vk.nPublic + 1}`);
    process.exit(2);
  }

  const alphaG1 = g1ToBytes(vk.vk_alpha_1);
  const betaG2  = g2ToBytes(vk.vk_beta_2);
  const gammaG2 = g2ToBytes(vk.vk_gamma_2);
  const deltaG2 = g2ToBytes(vk.vk_delta_2);

  const banner = "// Generated by build-verifier-constants.ts — do not edit by hand.\n" +
                 `// Source: circuits/verification_key.json (nPublic=${vk.nPublic})\n` +
                 "// Layout matches groth16-solana 0.2.0 Groth16Verifyingkey.\n\n" +
                 "use groth16_solana::groth16::Groth16Verifyingkey;\n\n";

  const body = [
    emitG1("VK_ALPHA_G1", alphaG1),
    emitG2("VK_BETA_G2",  betaG2),
    emitG2("VK_GAMME_G2", gammaG2),  // typo "gamme" matches the crate
    emitG2("VK_DELTA_G2", deltaG2),
    emitIC(vk.IC),
    [
      "pub const VERIFYING_KEY: Groth16Verifyingkey = Groth16Verifyingkey {",
      `    nr_pubinputs: ${vk.nPublic},`,
      "    vk_alpha_g1: VK_ALPHA_G1,",
      "    vk_beta_g2: VK_BETA_G2,",
      "    vk_gamme_g2: VK_GAMME_G2,",
      "    vk_delta_g2: VK_DELTA_G2,",
      "    vk_ic: &VK_IC,",
      "};",
    ].join("\n"),
    [
      "#[cfg(test)]",
      "mod tests {",
      "    use super::*;",
      "    #[test]",
      "    fn vk_byte_lengths_correct() {",
      "        assert_eq!(VERIFYING_KEY.vk_alpha_g1.len(), 64);",
      "        assert_eq!(VERIFYING_KEY.vk_beta_g2.len(), 128);",
      "        assert_eq!(VERIFYING_KEY.vk_gamme_g2.len(), 128);",
      "        assert_eq!(VERIFYING_KEY.vk_delta_g2.len(), 128);",
      `        assert_eq!(VERIFYING_KEY.vk_ic.len(), ${vk.nPublic + 1});`,
      `        assert_eq!(VERIFYING_KEY.nr_pubinputs as usize, ${vk.nPublic});`,
      "    }",
      "}",
    ].join("\n"),
  ].join("\n\n");

  writeFileSync(OUT_PATH, banner + body + "\n");
  console.log(`wrote ${OUT_PATH}`);
  console.log(`  nPublic=${vk.nPublic}  IC=${vk.IC.length}`);
}

main();
